apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-dev-web-depl
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: projet-dev-web
  template:
    metadata:
      labels:
        app: projet-dev-web
    spec:
      containers:
        - name: projet-dev-web-container
          image: projet-dev-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: projet-dev-web-service
spec:
  type: NodePort
  selector:
    app: projet-dev-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007