name: Deploiement Automatique FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploiement sur AlwaysData
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Récupération du code
      uses: actions/checkout@v4

    - name: 📂 Envoi des fichiers via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /www/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          config/config.example.php