name: Deploiement Automatique SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploiement sur AlwaysData
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Récupération du code
      uses: actions/checkout@v4

    - name: 🗑️ Nettoyage avant envoi
      run: rm -rf .git config/config.example.php

    - name: 📂 Envoi des fichiers via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        local_path: './'
        remote_path: '/www/'